# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/image-display-control"
    schedule:
      interval: "daily"

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - "*"
