# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/image-display-control"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    ignore:
      # @open-wc/testing 4.0.0 fails with
      # Could not find a declaration file for module '@open-wc/scoped-elements/html-element.js'
      - dependency-name: "@open-wc/testing"
        update-types: ["version-update:semver-major"]

      # eslint's CLI changed a lot in eslint@9. Staying on eslint@8 for now.
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - "*"
